version: '3'
services:
    node:
        build:
            context: .
            dockerfile: dockerfile-node
        container_name: ${PROJECT}-node
        restart: always
        expose:
            - '3000'
        command:
            "yarn start"
    nginx:
        image: ${REGISTRY}/${PROJECT}/nginx
        build:
            context: .
            dockerfile: dockerfile-nginx
        container_name: ${PROJECT}-nginx
        environment:
            - VIRTUAL_HOST=${PROJECT}.local
            - PROJECT=${PROJECT}
        command: /bin/sh -c "chown -R 1000:1000 /app && envsubst '$$VIRTUAL_HOST,$$PROJECT,$$API_SERVER' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
          - node
networks:
  default:
    external:
      name: nginx-proxy