version: '3'
services:
    nginx:
        expose:
            - '80'
            - '443'
        environment:
            - VIRTUAL_HOST=${VIRTUAL_NAME}.staging.netcore.lv
            - LETSENCRYPT_HOST=${VIRTUAL_NAME}.staging.netcore.lv
            - LETSENCRYPT_EMAIL=developers@netcore.lv
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http
