version: '3'
services:
    nginx:
        expose:
            - "80"
        command: /bin/sh -c "envsubst '$$VIRTUAL_HOST,$$PROJECT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"